apiVersion: v1
kind: Pod
metadata:
  name: "my-nginx"
  namespace: default
  labels:
    app: "my-nginx"
spec:
  containers:
  - name: my-nginx
    image: "docker.io/library/nginx:latest"
    # 三种策略 Always(总是拉远程) Never(只使用本地)  IfNotPresent(优先本地, 无就拉取远程, 不配置默认的选项)
    imagePullPolicy: IfNotPresent
    resources:
      # 限制资源
      limits:
        cpu: 100m
        memory: 100Mi
      # 要求的最小资源  
      requests:
        cpu: 100m
        memory: 100Mi
    ports:
    # 容器暴露端口
    - containerPort:  80
      name:  http
  restartPolicy: Always