---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - nginx-g.cdhome.com
  resources:
  - mynginxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nginx-g.cdhome.com
  resources:
  - mynginxes/finalizers
  verbs:
  - update
- apiGroups:
  - nginx-g.cdhome.com
  resources:
  - mynginxes/status
  verbs:
  - get
  - patch
  - update
