# 1. eval $(minikube docker-env)  minikube 使用 docker 里面的镜像
# 2. minikube docker-env -u  取消上面操作
apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  containers:
    - name: my-app
      image: my-app:v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8999
      resources:
        limits:
          cpu: 10m
          memory: 20Mi
        requests:
          cpu: 10m
          memory: 20Mi
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-svc
spec:
  selector:
    app: my-app
  ports:
    - port: 8999
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: my-app-svc
                port:
                  number: 8999
---

# 1. brew install minikube
# 2. minikube start/stop
# 3. minikube dashboard
# 4. minikube addons list/enable
# 5. minikube tunnel

# kubectl get nodes
# kubectl get pods -n[namespace] -o wide
# kubectl apply[delete] -f xx.yaml
# kubectl get svc[service]
# kubectl get deploy
# kubectl get ingress